Update for react-native >0.60.0
callstack/react-native-fbads pull request #275
Opened 2021-01-22 11:42 UTC by haxonadora

### Summary

Updated `android` and `ios` apps to support newest `react-native`
Updated example app to use `react-native` `0.63.4`

2021-01-22 11:47 UTC, troZee requested changes

2021-01-22 11:47 UTC, troZee commented on example/android/app/build.gradle
> +            storeFile file('debug.keystore')
Probably you dont need it :D

2021-01-22 12:02 UTC, mrousavy requested changes
Left some comments, please take a look. Thanks for your contribution, it was about time the example gets upgraded from the stone age to RN 0.63

2021-01-22 12:02 UTC, mrousavy commented on example/package.json
> +    "react-native-fbads": "^6.3.1",
Could you please let it point to the local version again? Otherwise we can't test yet-unpublished (local) changes in the example app

2021-01-22 12:02 UTC, mrousavy commented on example/package.json
> +    "react-native-reanimated": "^1.13.2",
Why did you install those libraries?

2021-01-22 12:02 UTC, mrousavy commented on example/package.json
> +    "react-native-screens": "^2.15.2"
Why did you install rn-screens?

2021-01-22 13:11 UTC, haxonadora commented on example/android/build.gradle
> +        classpath("com.android.tools.build:gradle:3.5.3")
this version is used when initiating project with `react-native init`. I can change it back to `4.0.1` and try if it works fine

2021-01-22 13:12 UTC, haxonadora commented on example/android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-all.zip
same as above, its the default configuration provided by `react-native init`

2021-02-02 11:10 UTC, mrousavy approved these changes
if everything works as expected on iOS **and** Android it looks fine for me now 👍

2021-02-02 12:05 UTC, mrousavy commented on example/ios/Podfile
>    pod 'ReactNativeAdsFacebook', :path => '../node_modules/react-native-fbads'
We can remove those as well (they both have .podspecs so they're automatically linked)

2021-02-03 09:51 UTC, thymikee commented
> width of this ad is equal to 1 (it's coming from FBAdView). Therefore there is an error with code 1011 :(. It happens only for rectangle banner view

@TMaszko let's tackle this as a followup

2021-02-03 09:52 UTC, merged